# mkdocs.yml

site_name: khcolors documentation

site_url: https://pykhaz.github.io/khcolors/

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark

  features:
    - content.code.copy

extra_css:
  - stylesheets/extra.css

use_directory_urls: false

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      # linenums: true
      anchor_linenums: true
  - pymdownx.snippets
  - footnotes

# markdown_extensions:
#   - pymdownx.superfences
#   - pymdownx.highlight:
#   - codehilite:
#       linenums: true
#       hl_lines: true        # Umożliwia podświetlanie wybranych linii
#   - pymdownx.snippets:
#   - footnotes

plugins:
  - search
  - macros
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            heading_level: 0
  # - footnotes  # Usuń, jeśli nadal powoduje błąd

nav:
  - khcolors documentation: index.md
  - tutorials.md
  - how-to-guides.md
  - reference.md
  - explanation.md

extra:
  tutorials_getting_started: "Getting started"

