# mkdocs.yml

site_name: khcolors documentation

theme:
  name: "material"

use_directory_urls: false

plugins:
  - search
  - macros  # for variables
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            heading_level: 0  # No heading for module # for docstring import

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - footnotes

nav:
  - khcolors documentation: index.md
  - tutorials.md
  - how-to-guides.md
  - reference.md
  - explanation.md

extra:
  tutorials_getting_started: "Getting started"
