name: Publish Python package to PyPI

on:
  push:
    tags:
      - 'v*'  # Uruchomi publikację na PyPI dla każdego taga, np. v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Hatch
        run: pip install hatch

      - name: Build and publish to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          hatch build
          hatch publish --token $PYPI_TOKEN

